# Generated by Django 4.0.4 on 2022-05-17 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='banner_imgs/', verbose_name='صورة')),
                ('alt_text', models.CharField(max_length=300, verbose_name='نص')),
            ],
            options={
                'verbose_name_plural': '1. اعلان',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='اسم الماركة')),
                ('image', models.ImageField(upload_to='brand_imgs/', verbose_name='صورة الماركة')),
            ],
            options={
                'verbose_name_plural': '3. الماركات',
            },
        ),
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amt', models.FloatField(verbose_name='اجمالي السعر')),
                ('paid_status', models.BooleanField(default=False, verbose_name='تم الدفع')),
                ('order_dt', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('order_status', models.CharField(choices=[('في الانتظار', 'في الانتظار'), ('شحنها', 'شحنها'), ('تم التوصيل', 'تم التوصيل')], default='في الانتظار', max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
            options={
                'verbose_name_plural': '8. الاوردر',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('image', models.ImageField(upload_to='cat_imgs/', verbose_name='صورة الفئة')),
            ],
            options={
                'verbose_name_plural': '2. الفئات',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='اللون')),
                ('color_code', models.CharField(max_length=100, verbose_name='رمز اللون')),
            ],
            options={
                'verbose_name_plural': '4. الالوان',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='العدد')),
                ('slug', models.CharField(max_length=400)),
                ('specs', models.TextField(verbose_name='المواصفات')),
                ('status', models.BooleanField(default=True, verbose_name='الحالة')),
                ('is_featured', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brand', verbose_name='الماركة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='الفئة')),
            ],
            options={
                'verbose_name_plural': '6. المنتج',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='المساحة التخزينية')),
            ],
            options={
                'verbose_name_plural': '5. المساحة التخزينية',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='المنتج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
            options={
                'verbose_name_plural': 'المفضلة',
            },
        ),
        migrations.CreateModel(
            name='UserAddressBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=50, null=True, verbose_name='رقم الهاتف')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('status', models.BooleanField(default=False, verbose_name='تفعيل العنوان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
            options={
                'verbose_name_plural': 'عنوان العميل',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(verbose_name='تعليق')),
                ('review_rating', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=150, verbose_name='التقييم')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='المنتج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
            options={
                'verbose_name_plural': 'تقييم المنتج',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='السعر')),
                ('image', models.ImageField(null=True, upload_to='product_imgs/', verbose_name='الصورة')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.color', verbose_name='اللون')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='المنتج')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.size', verbose_name='المساحة التخزينية')),
            ],
            options={
                'verbose_name_plural': '7. سمات المنتج',
            },
        ),
        migrations.CreateModel(
            name='CartOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=150, verbose_name='رقم الفاتورة')),
                ('item', models.CharField(max_length=150, verbose_name='اسم المنتج')),
                ('image', models.CharField(max_length=200, verbose_name='صورة المنتج')),
                ('qty', models.IntegerField(verbose_name='العدد')),
                ('price', models.FloatField(verbose_name='السعر')),
                ('total', models.FloatField(verbose_name='اجمالي السعر')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cartorder', verbose_name='الاوردر')),
            ],
            options={
                'verbose_name_plural': '9. قائمة الطلبات',
            },
        ),
    ]
