# Generated by Django 4.0.4 on 2022-05-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cartorderitems_name_cartorderitems_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitems',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cartorderitems',
            name='number',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
