# Generated by Django 4.0.4 on 2022-05-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cartorder_name_alter_cartorder_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
