# Generated by Django 4.0.4 on 2022-05-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_brand_image_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specs2',
            field=models.TextField(blank=True, null=True, verbose_name='2المواصفات'),
        ),
        migrations.AddField(
            model_name='product',
            name='specs3',
            field=models.TextField(blank=True, null=True, verbose_name='3المواصفات'),
        ),
        migrations.AddField(
            model_name='product',
            name='specs4',
            field=models.TextField(blank=True, null=True, verbose_name='4المواصفات'),
        ),
        migrations.AddField(
            model_name='product',
            name='specs5',
            field=models.TextField(blank=True, null=True, verbose_name='5المواصفات'),
        ),
        migrations.AddField(
            model_name='product',
            name='specs6',
            field=models.TextField(blank=True, null=True, verbose_name='6المواصفات'),
        ),
    ]
