# Generated by Django 4.0.4 on 2022-06-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_product_specs2_product_specs3_product_specs4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='المواصفات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2المواصفات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='3المواصفات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='4المواصفات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs5',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='5المواصفات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs6',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='6المواصفات'),
        ),
    ]
