# Generated by Django 4.0.4 on 2022-06-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_product_specs_alter_product_specs2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='cash',
            field=models.CharField(default='كاش', max_length=50),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='visa',
            field=models.CharField(default='فيزا', max_length=50),
        ),
    ]
