# Generated by Django 4.0.4 on 2022-06-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_cartorder_cash_cartorder_visa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='cash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='visa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
