# Generated by Django 4.0.4 on 2022-06-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_cartorder_cash_alter_cartorder_visa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='cash',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='cash'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='visa',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='visa'),
        ),
    ]
