# Generated by Django 4.0.4 on 2022-06-11 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_cartorder_cash_alter_cartorder_visa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='visa',
        ),
    ]
