# Generated by Django 4.0.4 on 2022-06-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_cartorder_cash_remove_cartorder_visa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddressBook',
        ),
    ]
