# Generated by Django 4.0.4 on 2022-06-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_useraddressbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='pay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
